name: Docker Image CI
on:
  push:
    branches:
      - main
jobs:
  "Build NodeJS 14-chromium":
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd ./nodejs/14-chromium
        docker build . --file Dockerfile --tag 14-chromium-${GITHUB_SHA::8} --tag 14-chromium-latest
